[tool.poetry]
name = "django"
version = "0.1.0"
description = ""
authors = ["fr0st <fr0st1s747@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
